### ISSUE TITLE
Peer to peer review

### ISSUE THREAD

**Issue by martinkarugaba** [otmanTR/Leaderboard-Project#4]
- [x] In your `index.js` file line `line 2` and `line 4`, please consider removing the unused code (comments) from your file.
- [x] Please consider removing all unused code from `modules/takingId.js`. This will give you a clean codebase and in case of an error, it makes the debugging process easy.
:smiley: Happy coding.

**Comment by otmanTR** [comment]
Thank you for your good commits.
